### ISSUE TITLE
Create Submission UI

### ISSUE THREAD

**Issue by andrewzlchen** [stevens-tyr/frontend#9]
Currently, we have no interface for view previously submitted submissions on assignments. We need a UI for a professor to view submissions.

TODO:

1. Open a modal when a user clicks  on an assignment (make a new column/action, or click on the name?) on the `/dashboard/course/:cid/assignments` route.

![image](https://user-images.githubusercontent.com/15252988/55745950-7e7dfb80-5a06-11e9-980e-579989245907.png)

2. The modal should contain relevant information regarding the submission like the assignment's name, grade, # submissions etc.

**Comment by robherley** [comment]
added in #12
